# This workflow will install Python dependencies, run tests and lint with a variety of
# Python versions.

name: continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          flit install --deps=develop -s
      - name: Run unit tests with pytest
        run: |
          pytest | tee ./pytest-coverage.txt
      - name: Comment unit test coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ./pytest-junit.xml
      - name: Run YAPF style check on source and test code
        run: |
          yapf --diff --recursive ./src ./tests
      - name: Run Pylint linter on source and test code
        run: |
          pylint ./src ./tests
