# This workflow will install dependencies, run tests and lint with Python 3.8.

name: continuous integration

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Otherwise, it will fail to push refs to the destination repo.

      - name: Set up Python 3.8
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          flit install --deps=develop -s

      - name: Run unit tests with pytest
        # pytest-coverage.txt is required to properly report coverage in README.md.
        run: pytest | tee ./pytest-coverage.txt

      - name: Run YAPF style check on source and test code
        run: yapf --diff --recursive ./src ./tests

      - name: Run Pylint linter on source and test code
        run: pylint ./src ./tests

      - name: Generate unit test coverage report
        id: report-coverage
        uses: MishaKav/pytest-coverage-comment@v1.1.43
        with:
          hide-comment: true
          junitxml-path: ./pytest-junit.xml

      - name: Update README.md with coverage html
        run: sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.report-coverage.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to README.md
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update coverage on README.md
